apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sooptalent-prod
resources:
- namespace.yaml
- vault-static-secret.yaml
- ../../../base/sooptalent
images:
- name: lightstone1/soop-talent-server
  newName: lightstone1/soop-talent-server
  newTag: d50daef628d28b6878ab24c3f521f0e015d8c84f
