apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sooptalent-prod
resources:
- namespace.yaml
- vault-static-secret.yaml
- ../../../base/sooptalent
images:
- name: lightstone1/soop-talent-server
  newName: lightstone1/soop-talent-server
  newTag: c3f4c5836904e204d8a6df320e05b01ec9068c7f
