apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sooptalent-prod
resources:
- namespace.yaml
- vault-static-secret.yaml
- ../../../base/sooptalent
images:
- name: lightstone1/soop-talent-server
  newName: lightstone1/soop-talent-server
  newTag: 97d2ee28bb5eee2666d4ab203e45dd5008841191
